#include "tevox.h"
#include <ctype.h>
#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <sys/types.h>
static void *grow(void *p,size_t n,size_t w){if(!n)n=1;if(w&&n>SIZE_MAX/w){tv_print_error("allocation overflow");exit(1);}void *q=realloc(p,n*w);if(!q){tv_print_error("out of memory");exit(1);}return q;}
static char *dupstr(const char *s){char *q=strdup(s?s:"");if(!q){tv_print_error("out of memory");exit(1);}return q;}
static char *strip(char *s){while(*s&&isspace((unsigned char)*s))s++;char *e=s+strlen(s);while(e>s&&isspace((unsigned char)e[-1]))*--e=0;return s;}
static int tabs(char *s,char **f,int cap){int n=0;while(n<cap){f[n++]=s;char *t=strchr(s,'\t');if(!t)break;*t=0;s=t+1;}if(n)f[n-1]=strip(f[n-1]);return n;}
static int i64(const char *s,int64_t *v){char *e=NULL;errno=0;long long x=strtoll(s,&e,10);if(errno||e==s||*strip(e))return 0;*v=(int64_t)x;return 1;}
static int integer(const char *s,int *v){int64_t x;if(!i64(s,&x)||x<INT_MIN||x>INT_MAX)return 0;*v=(int)x;return 1;}
static char *directory(const char *p){const char *s=strrchr(p,'/');if(!s)return dupstr(".");if(s==p)return dupstr("/");size_t n=(size_t)(s-p);char *q=grow(NULL,n+1,1);memcpy(q,p,n);q[n]=0;return q;}
static char *resolve(const char *base,const char *p){if(p[0]=='/')return dupstr(p);size_t n=strlen(base)+strlen(p)+2;char *q=grow(NULL,n,1);snprintf(q,n,"%s/%s",base,p);return q;}
static TvContig *contig(TvGenome *g,const char *name){for(size_t i=0;i<g->n_contigs;i++)if(!strcmp(g->contigs[i].name,name))return &g->contigs[i];return NULL;}
static int genome_id(TvRun *r,const char *id){for(size_t i=0;i<r->n_genomes;i++)if(!strcmp(r->genomes[i].id,id))return (int)i;return -1;}
static int fasta_index(TvGenome *g){FILE *fp=fopen(g->fasta_path,"rb");if(!fp){tv_print_error("cannot open FASTA '%s': %s",g->fasta_path,strerror(errno));return -1;}char *line=NULL;size_t cap=0;ssize_t n;TvContig *c=NULL;int last=0,ln=0;while((n=getline(&line,&cap,fp))>=0){ln++;if(n&&line[0]=='>'){if(c&&last>c->line_bases){tv_print_error("%s:%d invalid FASTA line width",g->fasta_path,ln-1);goto fail;}char *name=strip(line+1),*sp=strpbrk(name," \t");if(sp)*sp=0;if(!*name||contig(g,name)){tv_print_error("%s:%d duplicate/empty contig",g->fasta_path,ln);goto fail;}if(g->n_contigs==g->cap_contigs){g->cap_contigs=g->cap_contigs?g->cap_contigs*2:16;g->contigs=grow(g->contigs,g->cap_contigs,sizeof(*g->contigs));}c=&g->contigs[g->n_contigs++];memset(c,0,sizeof(*c));c->name=dupstr(name);c->seq_offset=(int64_t)ftello(fp);last=0;continue;}if(!c){if(*strip(line)){tv_print_error("%s:%d sequence before header",g->fasta_path,ln);goto fail;}continue;}int bases=(int)n;while(bases&&(line[bases-1]=='\n'||line[bases-1]=='\r'))bases--;if(!bases)continue;if(!c->line_bases){c->line_bases=bases;c->line_bytes=(int)n;}else if(last!=c->line_bases){tv_print_error("%s:%d variable-width nonterminal FASTA",g->fasta_path,ln-1);goto fail;}else if(bases==c->line_bases&&(int)n!=c->line_bytes){tv_print_error("%s:%d inconsistent newlines",g->fasta_path,ln);goto fail;}for(int i=0;i<bases;i++)if(!isalpha((unsigned char)line[i])&&!strchr("*-.",line[i])){tv_print_error("%s:%d invalid FASTA character",g->fasta_path,ln);goto fail;}c->length+=bases;last=bases;}if(c&&last>c->line_bases){tv_print_error("%s:%d invalid final FASTA width",g->fasta_path,ln);goto fail;}free(line);fclose(fp);if(!g->n_contigs){tv_print_error("FASTA '%s' is empty",g->fasta_path);return -1;}return 0;fail:free(line);fclose(fp);return -1;}
static char *attr(const char *s,const char *key){size_t k=strlen(key);while(*s){while(*s==';'||isspace((unsigned char)*s))s++;const char *end=strchr(s,';');if(!end)end=s+strlen(s);const char *eq=memchr(s,'=',(size_t)(end-s));if(eq&&(size_t)(eq-s)==k&&!strncasecmp(s,key,k)){size_t n=(size_t)(end-eq-1);char *q=grow(NULL,n+1,1);memcpy(q,eq+1,n);q[n]=0;return q;}s=*end?end+1:end;}return NULL;}
static int push_te(TvGenome *g,TvTE *te,int ln){TvContig *c=contig(g,te->contig);if(!c||te->start<0||te->end<=te->start||te->end>c->length){tv_print_error("%s:%d annotation interval outside FASTA",g->te_path,ln);return -1;}if(g->n_tes==g->cap_tes){g->cap_tes=g->cap_tes?g->cap_tes*2:64;g->tes=grow(g->tes,g->cap_tes,sizeof(*g->tes));}g->tes[g->n_tes++]=*te;return 0;}
static int annotation(TvGenome *g,int gid){FILE *fp=fopen(g->te_path,"r");if(!fp){tv_print_error("cannot open annotation '%s': %s",g->te_path,strerror(errno));return -1;}int isgff=strstr(g->te_path,".gff")||strstr(g->te_path,".GFF");char *line=NULL;size_t cap=0;ssize_t z;int ln=0;while((z=getline(&line,&cap,fp))>=0){(void)z;ln++;char *row=strip(line);if(!*row||*row=='#')continue;char *f[16]={0};int n=tabs(row,f,16);if((isgff&&n<9)||(!isgff&&n<3)){tv_print_error("%s:%d malformed annotation",g->te_path,ln);goto fail;}TvTE te={.genome=gid,.strand='.'};te.contig=dupstr(f[0]);int64_t a,b;if(isgff){if(!i64(f[3],&a)||!i64(f[4],&b))goto bad;te.start=a-1;te.end=b;te.strand=*f[6]?*f[6]:'.';te.type=dupstr(f[2]);te.id=attr(f[8],"ID");if(!te.id)te.id=attr(f[8],"Name");te.family=attr(f[8],"family");if(!te.family)te.family=attr(f[8],"Family");if(!te.family)te.family=attr(f[8],"classification");}else{if(!i64(f[1],&a)||!i64(f[2],&b))goto bad;te.start=a;te.end=b;te.id=n>3&&*f[3]?dupstr(f[3]):NULL;te.strand=n>5&&*f[5]?*f[5]:'.';te.family=n>6&&*f[6]?dupstr(f[6]):NULL;te.type=n>7&&*f[7]?dupstr(f[7]):NULL;}if(!te.id){char id[160];snprintf(id,sizeof(id),"%s:%s:%lld-%lld",g->id,te.contig,(long long)te.start,(long long)te.end);te.id=dupstr(id);}if(!te.type)te.type=dupstr("transposable_element");if(!te.family)te.family=dupstr(TEVOX_UNKNOWN);if(push_te(g,&te,ln))goto bad;continue;bad:free(te.id);free(te.contig);free(te.type);free(te.family);tv_print_error("%s:%d invalid annotation record",g->te_path,ln);goto fail;}free(line);fclose(fp);if(!g->n_tes){tv_print_error("annotation '%s' contains no records",g->te_path);return -1;}return 0;fail:free(line);fclose(fp);return -1;}
void tv_run_init(TvRun *r){memset(r,0,sizeof(*r));r->cfg.flank=100;r->cfg.candidate_window=100;r->cfg.min_mapq=20;r->cfg.min_flank_fraction=.6;r->cfg.min_edge_score=45;r->cfg.max_n_fraction=.25;}
void tv_run_free(TvRun *r){for(size_t x=0;x<r->n_genomes;x++){TvGenome *g=&r->genomes[x];free(g->id);free(g->fasta_path);free(g->te_path);for(size_t i=0;i<g->n_contigs;i++)free(g->contigs[i].name);free(g->contigs);for(size_t i=0;i<g->n_tes;i++){free(g->tes[i].id);free(g->tes[i].contig);free(g->tes[i].type);free(g->tes[i].family);}free(g->tes);}for(size_t i=0;i<r->n_pafs;i++){free(r->pafs[i].qname);free(r->pafs[i].tname);free(r->pafs[i].ops);}for(size_t i=0;i<r->n_projections;i++)free(r->projections[i].contig);free(r->genomes);free(r->nodes);free(r->pafs);free(r->projections);free(r->edges);free(r->components);memset(r,0,sizeof(*r));}
int tv_add_genome(TvRun *r,const char *id,const char *fa,const char *ann,int copies){if(!id||!*id||genome_id(r,id)>=0||copies<1){tv_print_error("genome IDs must be unique and copy quota positive");return -1;}if(r->n_genomes==r->cap_genomes){r->cap_genomes=r->cap_genomes?r->cap_genomes*2:8;r->genomes=grow(r->genomes,r->cap_genomes,sizeof(*r->genomes));}int idx=(int)r->n_genomes;TvGenome *g=&r->genomes[r->n_genomes++];memset(g,0,sizeof(*g));g->id=dupstr(id);g->fasta_path=dupstr(fa);g->te_path=dupstr(ann);g->max_locus_copies=copies;if(fasta_index(g)||annotation(g,idx))return -1;return idx;}
int tv_load_manifest(TvRun *r,const char *path){FILE *fp=fopen(path,"r");if(!fp){tv_print_error("cannot open manifest '%s'",path);return -1;}char *base=directory(path),*line=NULL;size_t cap=0;ssize_t z;int ln=0;while((z=getline(&line,&cap,fp))>=0){(void)z;ln++;char *row=strip(line);if(!*row||*row=='#')continue;char *f[5]={0};int n=tabs(row,f,5);if(!strcmp(f[0],"genome_id"))continue;if(n<3||n>4){tv_print_error("%s:%d expected 3 or 4 columns",path,ln);goto fail;}int copies=1;if(n==4&&(!integer(f[3],&copies)||copies<1)){tv_print_error("%s:%d invalid quota",path,ln);goto fail;}char *fa=resolve(base,f[1]),*an=resolve(base,f[2]);int ok=tv_add_genome(r,f[0],fa,an,copies);free(fa);free(an);if(ok<0)goto fail;}free(base);free(line);fclose(fp);if(r->n_genomes<2){tv_print_error("manifest needs at least two genomes");return -1;}return 0;fail:free(base);free(line);fclose(fp);return -1;}
static int cigar(const char *s,TvCigarOp **out,size_t *nout,int64_t qs,int64_t ts){TvCigarOp *op=NULL;size_t n=0,cap=0;int64_t q=0,t=0;while(*s){char *e=NULL;errno=0;long long z=strtoll(s,&e,10);if(errno||e==s||z<=0||!*e)goto bad;char c=*e++;if(!strchr("M=XID",c))goto bad;if(n==cap){cap=cap?cap*2:16;op=grow(op,cap,sizeof(*op));}op[n++]=(TvCigarOp){c,(int64_t)z};if(strchr("M=XI",c))q+=z;if(strchr("M=XD",c))t+=z;s=e;}if(!n||q!=qs||t!=ts)goto bad;*out=op;*nout=n;return 0;bad:free(op);return -1;}
static void push_paf(TvRun *r,TvPaf *p){if(r->n_pafs==r->cap_pafs){r->cap_pafs=r->cap_pafs?r->cap_pafs*2:128;r->pafs=grow(r->pafs,r->cap_pafs,sizeof(*r->pafs));}r->pafs[r->n_pafs++]=*p;}
static void reverse_paf(TvRun *r,const TvPaf *s){TvPaf p={.query_genome=s->target_genome,.target_genome=s->query_genome,.qname=dupstr(s->tname),.qlen=s->tlen,.qstart=s->tstart,.qend=s->tend,.strand=s->strand,.tname=dupstr(s->qname),.tlen=s->qlen,.tstart=s->qstart,.tend=s->qend,.matches=s->matches,.block_len=s->block_len,.mapq=s->mapq,.n_ops=s->n_ops};p.ops=grow(NULL,p.n_ops,sizeof(*p.ops));for(size_t i=0;i<p.n_ops;i++){size_t j=s->strand=='-'?s->n_ops-i-1:i;p.ops[i]=s->ops[j];if(p.ops[i].code=='I')p.ops[i].code='D';else if(p.ops[i].code=='D')p.ops[i].code='I';}push_paf(r,&p);}
int tv_add_paf_file(TvRun *r,int qg,int tg,const char *path){if(qg<0||tg<0||qg==(int)tg||qg>=(int)r->n_genomes||tg>=(int)r->n_genomes)return -1;FILE *fp=fopen(path,"r");if(!fp){tv_print_error("cannot open PAF '%s'",path);return -1;}char *line=NULL;size_t cap=0;ssize_t z;int ln=0,records=0;while((z=getline(&line,&cap,fp))>=0){(void)z;ln++;char *row=strip(line);if(!*row||*row=='#')continue;char *f[128]={0};int n=tabs(row,f,128);if(n<12){tv_print_error("%s:%d PAF requires 12 fields",path,ln);goto fail;}TvPaf p={.query_genome=qg,.target_genome=tg,.qname=dupstr(f[0]),.strand=*f[4],.tname=dupstr(f[5])};if(!i64(f[1],&p.qlen)||!i64(f[2],&p.qstart)||!i64(f[3],&p.qend)||!i64(f[6],&p.tlen)||!i64(f[7],&p.tstart)||!i64(f[8],&p.tend)||!i64(f[9],&p.matches)||!i64(f[10],&p.block_len)||!integer(f[11],&p.mapq)||(p.strand!='+'&&p.strand!='-')||p.qstart<0||p.qend<=p.qstart||p.tstart<0||p.tend<=p.tstart||p.qend>p.qlen||p.tend>p.tlen)goto record_bad;TvContig *qc=contig(&r->genomes[qg],p.qname),*tc=contig(&r->genomes[tg],p.tname);if(!qc||!tc||qc->length!=p.qlen||tc->length!=p.tlen)goto record_bad;const char *cg=NULL;for(int i=12;i<n;i++)if(!strncmp(f[i],"cg:Z:",5))cg=f[i]+5;if(!cg||cigar(cg,&p.ops,&p.n_ops,p.qend-p.qstart,p.tend-p.tstart))goto record_bad;push_paf(r,&p);reverse_paf(r,&p);records++;continue;record_bad:free(p.qname);free(p.tname);free(p.ops);tv_print_error("%s:%d invalid PAF or missing cg:Z",path,ln);goto fail;}free(line);fclose(fp);if(!records){tv_print_error("PAF '%s' contains no records",path);return -1;}return 0;fail:free(line);fclose(fp);return -1;}
int tv_load_alignments(TvRun *r,const char *path){FILE *fp=fopen(path,"r");if(!fp){tv_print_error("cannot open alignments table '%s'",path);return -1;}char *base=directory(path),*line=NULL;size_t cap=0;ssize_t z;int ln=0,pairs=0;while((z=getline(&line,&cap,fp))>=0){(void)z;ln++;char *row=strip(line);if(!*row||*row=='#')continue;char *f[4]={0};int n=tabs(row,f,4);if(!strcmp(f[0],"query_id"))continue;if(n!=3){tv_print_error("%s:%d expected three columns",path,ln);goto fail;}int q=genome_id(r,f[0]),t=genome_id(r,f[1]);if(q<0||t<0||q==t)goto fail;char *p=resolve(base,f[2]);int ok=tv_add_paf_file(r,q,t,p);free(p);if(ok)goto fail;pairs++;}free(base);free(line);fclose(fp);if(!pairs){tv_print_error("alignment table is empty");return -1;}return 0;fail:free(base);free(line);fclose(fp);return -1;}
