#include "tevox.h"
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
typedef struct { const char *manifest,*alignments,*output,*genome_a,*fasta_a,*te_a,*genome_b,*fasta_b,*te_b,*paf; int copies_a,copies_b; } Args;
static void usage(FILE *f){fprintf(f,"TEvoX %s - uncertainty-aware TE locus reconstruction\n\nUsage:\n  tevox graph --manifest genomes.tsv --alignments alignments.tsv [options]\n  tevox pair --genome-a A --fasta-a A.fa --te-a A.gff3 --genome-b B --fasta-b B.fa --te-b B.gff3 --paf A_B.paf [options]\n\nOptions:\n  -o, --output PREFIX       output prefix (default: tevox)\n  --flank INT               flank length (100)\n  --candidate-window INT    candidate window (100)\n  --min-mapq INT            minimum MAPQ (20)\n  --min-flank FLOAT         paired-flank fraction (0.60)\n  --min-edge FLOAT          graph edge threshold (45)\n  --max-n FLOAT             maximum N fraction (0.25)\n  --max-copies-a/b INT      pair-mode WGD quota\n  -v, --verbose\n",TEVOX_VERSION);}
static const char *value(int n,char **v,int *i){if(*i+1>=n){tv_print_error("option '%s' requires a value",v[*i]);return NULL;}return v[++*i];}
static int number(const char *s,long *x){char *e=NULL;errno=0;*x=strtol(s,&e,10);return !errno&&e!=s&&!*e;}
static int decimal(const char *s,double *x){char *e=NULL;errno=0;*x=strtod(s,&e);return !errno&&e!=s&&!*e;}
static int options(int n,char **v,Args *a,TvConfig *c){for(int i=2;i<n;i++){const char *o=v[i],*x=NULL;if(!strcmp(o,"-h")||!strcmp(o,"--help"))return 1;if(!strcmp(o,"-v")||!strcmp(o,"--verbose")){c->verbose=true;continue;}if(!(x=value(n,v,&i)))return -1;if(!strcmp(o,"--manifest"))a->manifest=x;else if(!strcmp(o,"--alignments"))a->alignments=x;else if(!strcmp(o,"-o")||!strcmp(o,"--output"))a->output=x;else if(!strcmp(o,"--genome-a"))a->genome_a=x;else if(!strcmp(o,"--fasta-a"))a->fasta_a=x;else if(!strcmp(o,"--te-a"))a->te_a=x;else if(!strcmp(o,"--genome-b"))a->genome_b=x;else if(!strcmp(o,"--fasta-b"))a->fasta_b=x;else if(!strcmp(o,"--te-b"))a->te_b=x;else if(!strcmp(o,"--paf"))a->paf=x;else if(!strcmp(o,"--flank")){long z;if(!number(x,&z)||z<1||z>1000000)goto bad;c->flank=(int)z;}else if(!strcmp(o,"--candidate-window")){long z;if(!number(x,&z)||z<0||z>1000000)goto bad;c->candidate_window=(int)z;}else if(!strcmp(o,"--min-mapq")){long z;if(!number(x,&z)||z<0||z>255)goto bad;c->min_mapq=(int)z;}else if(!strcmp(o,"--max-copies-a")){long z;if(!number(x,&z)||z<1||z>1000)goto bad;a->copies_a=(int)z;}else if(!strcmp(o,"--max-copies-b")){long z;if(!number(x,&z)||z<1||z>1000)goto bad;a->copies_b=(int)z;}else if(!strcmp(o,"--min-flank")){if(!decimal(x,&c->min_flank_fraction)||c->min_flank_fraction<0||c->min_flank_fraction>1)goto bad;}else if(!strcmp(o,"--min-edge")){if(!decimal(x,&c->min_edge_score)||c->min_edge_score<0||c->min_edge_score>100)goto bad;}else if(!strcmp(o,"--max-n")){if(!decimal(x,&c->max_n_fraction)||c->max_n_fraction<0||c->max_n_fraction>1)goto bad;}else{tv_print_error("unknown option '%s'",o);return -1;}continue;bad:tv_print_error("invalid value '%s' for option '%s'",x,o);return -1;}return 0;}
int main(int n,char **v){if(n==2&&!strcmp(v[1],"--version")){printf("tevox %s\n",TEVOX_VERSION);return 0;}if(n<2||!strcmp(v[1],"-h")||!strcmp(v[1],"--help")){usage(n<2?stderr:stdout);return n<2?2:0;}int graph=!strcmp(v[1],"graph"),pair=!strcmp(v[1],"pair");if(!graph&&!pair){tv_print_error("expected subcommand 'graph' or 'pair'");return 2;}TvRun r;tv_run_init(&r);Args a={.output="tevox",.copies_a=1,.copies_b=1};int p=options(n,v,&a,&r.cfg);if(p==1){usage(stdout);tv_run_free(&r);return 0;}int ok=0;if(p<0)ok=-1;else if(graph){if(!a.manifest||!a.alignments){tv_print_error("graph requires --manifest and --alignments");ok=-1;}else if(tv_load_manifest(&r,a.manifest)||tv_load_alignments(&r,a.alignments))ok=-1;}else{if(!a.genome_a||!a.fasta_a||!a.te_a||!a.genome_b||!a.fasta_b||!a.te_b||!a.paf){tv_print_error("pair requires both genomes, FASTAs, annotations and --paf");ok=-1;}else{int x=tv_add_genome(&r,a.genome_a,a.fasta_a,a.te_a,a.copies_a),y=tv_add_genome(&r,a.genome_b,a.fasta_b,a.te_b,a.copies_b);if(x<0||y<0||tv_add_paf_file(&r,x,y,a.paf))ok=-1;}}if(!ok&&(tv_analyze(&r)||tv_write_outputs(&r,a.output)))ok=-1;if(!ok){printf("TEvoX reconstructed %d locus/loci across %zu genomes.\n",r.n_loci,r.n_genomes);printf("Outputs: %s.{edges,loci,states,summary}.tsv\n",a.output);}tv_run_free(&r);return ok?1:0;}
