#include "tevox.h"
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
typedef struct { TvState state; double quality; int copies; const TvProjection *p; } Call;
static Call call(TvRun *r,int locus,int genome){Call c={.state=TV_UNCALLABLE};double es=0;for(size_t i=0;i<r->n_nodes;i++)if(r->components[i]==locus&&r->nodes[i].genome==genome)c.copies++;if(c.copies){c.state=TV_PRESENT_ANNOTATED;for(size_t i=0;i<r->n_edges;i++){TvEdge *e=&r->edges[i];if(e->selected&&(r->components[e->a]==locus||r->components[e->b]==locus)&&e->score>es)es=e->score;}c.quality=es?70+.3*es:70;return c;}const TvProjection *second=NULL;for(size_t i=0;i<r->n_projections;i++){TvProjection *p=&r->projections[i];if(p->target_genome!=genome||r->components[p->source_te]!=locus)continue;if(!c.p||p->quality>c.p->quality){second=c.p;c.p=p;}else if(!second||p->quality>second->quality)second=p;}if(c.p){c.state=c.p->state;c.quality=c.p->quality;if(c.p->target_te>=0&&r->components[c.p->target_te]!=locus&&c.state==TV_PRESENT_ANNOTATED){c.state=TV_PROJECTION_AMBIGUOUS;c.quality*=.75;}if(second&&second->quality>=c.quality-5&&(strcmp(second->contig,c.p->contig)||llabs(second->start-c.p->start)>r->cfg.candidate_window)){c.state=TV_PROJECTION_AMBIGUOUS;c.quality*=.75;}}return c;}
static FILE *openout(const char *pre,const char *suf,char **path){size_t n=strlen(pre)+strlen(suf)+1;*path=malloc(n);if(!*path)return NULL;snprintf(*path,n,"%s%s",pre,suf);FILE *f=fopen(*path,"w");if(!f){tv_print_error("cannot write '%s': %s",*path,strerror(errno));free(*path);*path=NULL;}return f;}
static void members(FILE *f,TvRun *r,int locus,int field){int first=1;for(size_t i=0;i<r->n_nodes;i++){if(r->components[i]!=locus)continue;if(!first)fputc(',',f);first=0;TvTE *t=&r->nodes[i];if(field==0)fprintf(f,"%s:%s",r->genomes[t->genome].id,t->id);else if(field==1)fprintf(f,"%s",t->family);else fprintf(f,"%s:%lld-%lld",t->contig,(long long)t->start,(long long)t->end);}if(first)fputc('.',f);}
static void present(FILE *f,TvRun *r,int locus,int genome,int field){int first=1;for(size_t i=0;i<r->n_nodes;i++){TvTE *t=&r->nodes[i];if(r->components[i]!=locus||t->genome!=genome)continue;if(!first)fputc(',',f);first=0;if(field==0)fprintf(f,"%s",t->id);else if(field==1)fprintf(f,"%s",t->contig);else if(field==2)fprintf(f,"%lld",(long long)t->start);else fprintf(f,"%lld",(long long)t->end);}if(first)fputc('.',f);}
static int write_edges(TvRun *r,const char *pre){char *p=NULL;FILE *f=openout(pre,".edges.tsv",&p);if(!f)return -1;fprintf(f,"te_a\tgenome_a\tte_b\tgenome_b\tscore\treciprocal\tfamily_match\tbreakpoint_distance\tselected\n");for(size_t i=0;i<r->n_edges;i++){TvEdge *e=&r->edges[i];TvTE *a=&r->nodes[e->a],*b=&r->nodes[e->b];fprintf(f,"%s\t%s\t%s\t%s\t%.2f\t%s\t%s\t%d\t%s\n",a->id,r->genomes[a->genome].id,b->id,r->genomes[b->genome].id,e->score,e->reciprocal?"true":"false",e->family_match?"true":"false",e->breakpoint_distance,e->selected?"true":"false");}fclose(f);free(p);return 0;}
static int write_loci(TvRun *r,const char *pre){char *p=NULL;FILE *f=openout(pre,".loci.tsv",&p);if(!f)return -1;fprintf(f,"locus_id\tmember_count\tgenome_count\tmembers\tfamilies\tcoordinates\tquality\n");for(int l=0;l<r->n_loci;l++){int m=0,gc=0;double q=0;for(size_t i=0;i<r->n_nodes;i++)if(r->components[i]==l)m++;for(size_t g=0;g<r->n_genomes;g++){Call c=call(r,l,(int)g);if(c.copies)gc++;q+=c.quality;}fprintf(f,"TEL%06d\t%d\t%d\t",l+1,m,gc);members(f,r,l,0);fputc('\t',f);members(f,r,l,1);fputc('\t',f);members(f,r,l,2);fprintf(f,"\t%.2f\n",q/(double)r->n_genomes);}fclose(f);free(p);return 0;}
static int write_states(TvRun *r,const char *pre){char *p=NULL;FILE *f=openout(pre,".states.tsv",&p);if(!f)return -1;fprintf(f,"locus_id\tgenome_id\tstate\tquality\tcopy_count\tmember_ids\tcontig\tstart\tend\tidentity\tleft_flank\tright_flank\tn_fraction\tmapq\tevidence\n");for(int l=0;l<r->n_loci;l++)for(size_t g=0;g<r->n_genomes;g++){Call c=call(r,l,(int)g);fprintf(f,"TEL%06d\t%s\t%s\t%.2f\t%d\t",l+1,r->genomes[g].id,tv_state_name(c.state),c.quality,c.copies);if(c.copies){present(f,r,l,(int)g,0);fputc('\t',f);present(f,r,l,(int)g,1);fputc('\t',f);present(f,r,l,(int)g,2);fputc('\t',f);present(f,r,l,(int)g,3);fprintf(f,"\t.\t.\t.\t.\t.\tANNOTATED_COMPONENT\n");}else if(c.p){fprintf(f,".\t%s\t%lld\t%lld\t%.4f\t%.4f\t%.4f\t%.4f\t%d\t%s\n",c.p->contig,(long long)c.p->start,(long long)c.p->end,c.p->identity,c.p->left_flank,c.p->right_flank,c.p->n_fraction,c.p->mapq,c.state==TV_PROJECTION_AMBIGUOUS&&c.p->state!=TV_PROJECTION_AMBIGUOUS?"CONFLICTING_COMPONENT_PROJECTIONS":c.p->evidence);}else fprintf(f,".\t.\t.\t.\t.\t.\t.\t.\t.\tNO_EVIDENCE\n");}fclose(f);free(p);return 0;}
static int write_summary(TvRun *r,const char *pre){char *p=NULL;FILE *f=openout(pre,".summary.tsv",&p);if(!f)return -1;fprintf(f,"genome_id\tstate\tcount\n");for(size_t g=0;g<r->n_genomes;g++){int n[TV_UNCALLABLE+1]={0};for(int l=0;l<r->n_loci;l++)n[call(r,l,(int)g).state]++;for(int s=0;s<=TV_UNCALLABLE;s++)fprintf(f,"%s\t%s\t%d\n",r->genomes[g].id,tv_state_name((TvState)s),n[s]);}fclose(f);free(p);return 0;}
int tv_write_outputs(TvRun *r,const char *pre){if(!pre||!*pre)return -1;return write_edges(r,pre)||write_loci(r,pre)||write_states(r,pre)||write_summary(r,pre)?-1:0;}
